### ISSUE TITLE
unsubscribe?

### ISSUE THREAD

**Issue by literalpie** [KenAKAFrosty/qwik-realtime#1]
Hi, I'm interested in [the pattern used to stream updates](https://github.com/KenAKAFrosty/qwik-realtime/blob/main/src/routes/realtime-chat.ts#L25) to a qwik app. However, I don't see any sort of unsubscribe logic. It seems like every time the app is loaded, it will create a new loop on the server that will never finish. Is this a known limitation of the current implementation, or am I missing something?

**Comment by KenAKAFrosty** [comment]
Definitely just a known limitation of this - this was my first little dabble into using the async generators for streaming updates. 

That culminated in the much more built-out (but still very very new): https://github.com/KenAKAFrosty/qwik-living-data

That one was also designed to work smartly with edge functions and not rely on an approach like this. It includes things like pausing, changing the interval, etc. 

In both cases though I hope it at least helps explore the async generator to stream updates pattern. I've found it very very very nice to use!

**Comment by literalpie** [comment]
Super cool! Thanks for sharing!
